services:
  mongo:
    image: mongo:7
    container_name: crud-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    image: ${DOCKERHUB_USERNAME}/crud-dd-backend:latest
    container_name: crud-backend
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/dd_db
      - PORT=8080
    depends_on:
      - mongo

  frontend:
    image: ${DOCKERHUB_USERNAME}/crud-dd-frontend:latest
    container_name: crud-frontend
    restart: unless-stopped
    depends_on:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: crud-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
